const chapters = [
  {
    id: 1, n: "I", t: "Crack Spreads Fundamentals", d: "Understand the core profitability indicator of every refinery — the crack spread — and learn how traders and refiners use it to gauge margins in real time.",
    concepts: [
      { t: "What Is a Crack Spread?", h: "The refiner's heartbeat, measured in dollars per barrel.", b: "A crack spread is the difference between the price of refined petroleum products and the price of crude oil, representing the gross margin a refinery earns from 'cracking' crude into products. It is quoted in $/bbl and is the single most watched indicator of refinery profitability across global markets. When Brent crude is $80/bbl and gasoline sells at $95/bbl equivalent, the simple gasoline crack is $15/bbl.", x: "Crack spreads are traded as futures on NYMEX and ICE, allowing refiners to hedge their margins months in advance. A refiner expecting to process 100,000 bbl/day can lock in a $12/bbl crack spread by selling product futures and buying crude futures simultaneously, guaranteeing roughly $1.2 million/day in gross margin regardless of where absolute prices move." },
      { t: "The 3-2-1 Crack Spread", h: "Three barrels in, two of gasoline, one of diesel — the industry's favorite shorthand.", b: "The 3-2-1 crack spread assumes 3 barrels of crude oil yield 2 barrels of gasoline and 1 barrel of distillate (diesel/heating oil), which roughly approximates a US refinery's output. The formula is: (2 x Gasoline price + 1 x Heating Oil price - 3 x Crude price) / 3. In 2022, the US Gulf Coast 3-2-1 crack hit an extraordinary $60/bbl during the post-COVID demand surge, versus a 10-year average of $15-20/bbl.", x: "The 3-2-1 ratio is most representative of US refineries which are gasoline-heavy due to the large light vehicle fleet. NYMEX RBOB gasoline and NY Harbor ULSD are the standard product benchmarks used. Traders monitor the 3-2-1 on both a prompt-month and forward-curve basis — a backwardated crack curve signals near-term tightness while contango suggests future margin pressure." },
      { t: "The 5-3-2 Crack Spread", h: "Asia's preferred formula — because the East runs on diesel, not gasoline.", b: "The 5-3-2 crack spread uses 5 barrels of crude to produce 3 barrels of middle distillates (gasoil/diesel) and 2 barrels of gasoline, reflecting the diesel-heavy demand profile of Asian and European markets. The formula is: (3 x Gasoil price + 2 x Gasoline price - 5 x Crude price) / 5. Singapore 5-3-2 cracks using Dubai crude typically range $5-12/bbl, spiking above $25/bbl during tight diesel markets.", x: "Indian refiners like Reliance Industries and IOCL track the Singapore 5-3-2 closely because it mirrors their product slate — India's diesel demand is roughly 40% of the petroleum product mix versus 15% for gasoline. The Dubai crude benchmark is used as the input because over 60% of India's crude imports come from the Middle East and are priced off Dubai/Oman." },
      { t: "Regional Crack Spread Variations", h: "Same barrel, different continent, wildly different margin.", b: "Crack spreads vary significantly by region due to differences in crude quality, product demand mix, refinery configuration, and regulatory standards. The US Gulf Coast (USGC) 3-2-1 crack using LLS crude typically runs $2-4/bbl higher than the Midwest (Group 3) crack because of export optionality. Northwest European cracks using Brent tend to run lower than USGC cracks due to higher energy costs and carbon pricing under the EU ETS.", x: "The Singapore complex margin is the key Asian benchmark published by Reuters and Platts, calculated using Dubai crude and a full product slate including naphtha, gasoline, jet, gasoil, and fuel oil. In 2023, the Singapore complex margin averaged $7-8/bbl while the USGC 3-2-1 averaged $28/bbl — the gap reflects US natural gas cost advantage ($3/MMBtu vs $12/MMBtu for Asian LNG) and the shale revolution's supply of cheap light sweet crude." },
      { t: "Historical Ranges & What Drives Swings", h: "From negative margins in 2020 to record profits in 2022 — crack spreads are volatile beasts.", b: "Over the past decade, the USGC 3-2-1 crack spread has ranged from -$5/bbl during COVID-19 demand destruction (April 2020) to over $60/bbl in June 2022 when global refinery capacity was tight and Russian product sanctions loomed. Normal operating range is $10-25/bbl, with seasonal peaks in summer driving season (gasoline) and winter (heating oil/diesel). Key drivers include refinery utilization rates, unplanned outages, product inventory levels, and geopolitical disruptions.", x: "The 2022 crack spread super-cycle was driven by a confluence of factors: 3 million bbl/day of global refinery capacity shut permanently during 2020-2021, Russian product exports (1.5 million bbl/day of diesel) faced sanctions, and Chinese refiners cut exports by 40%. Analysts at Goldman Sachs called it a 'structural shortage' of refining capacity. By 2024, new capacity from Nigeria's Dangote refinery (650,000 bbl/day), Kuwait's Al-Zour (615,000 bbl/day), and Saudi Arabia's Jazan (400,000 bbl/day) began normalizing cracks back toward $15-20/bbl." }
    ],
    quiz: [
      { q: "What does a crack spread measure?", o: ["The viscosity of crude oil after thermal cracking", "The difference between refined product prices and crude oil cost", "The energy required to distill one barrel of crude", "The sulfur content reduction during hydrocracking"], c: 1, e: "A crack spread measures the gross margin a refinery earns — the difference between the revenue from selling refined products and the cost of purchasing crude oil, expressed in $/bbl." },
      { q: "In the 3-2-1 crack spread formula, what is the assumed product yield?", o: ["3 barrels gasoline + 2 barrels diesel from 1 barrel crude", "2 barrels gasoline + 1 barrel diesel from 3 barrels crude", "1 barrel gasoline + 2 barrels diesel from 3 barrels crude", "3 barrels diesel + 2 barrels gasoline from 1 barrel crude"], c: 1, e: "The 3-2-1 formula assumes 3 barrels of crude produce 2 barrels of gasoline and 1 barrel of distillate (diesel/heating oil), approximating a typical US refinery's output ratio." },
      { q: "Why do Asian refiners prefer the 5-3-2 crack spread over the 3-2-1?", o: ["Asian crude is heavier and yields more residual fuel oil", "Asian markets are diesel-heavy, with distillates dominating demand", "The 5-3-2 is simpler to calculate for smaller refineries", "Asian gasoline quality standards require less processing"], c: 1, e: "Asia's demand profile is diesel-heavy — in India, diesel accounts for ~40% of product demand versus ~15% for gasoline. The 5-3-2 (3 distillate + 2 gasoline from 5 crude) better reflects this reality than the gasoline-heavy US 3-2-1." },
      { q: "What was the approximate USGC 3-2-1 crack spread at its 2022 peak?", o: ["$25/bbl", "$40/bbl", "$60/bbl", "$90/bbl"], c: 2, e: "The USGC 3-2-1 crack spread hit an extraordinary ~$60/bbl in June 2022, driven by permanent refinery closures during COVID, Russian sanctions, and Chinese export cuts — far above the 10-year average of $15-20/bbl." }
    ]
  },
  {
    id: 2, n: "II", t: "Gross Refinery Margin (GRM)", d: "Dive deep into GRM — the comprehensive profitability metric that captures a refinery's full product slate, not just a simplified crack spread proxy.",
    concepts: [
      { t: "GRM Definition vs Crack Spread", h: "Crack spread is the trailer — GRM is the full movie.", b: "Gross Refinery Margin (GRM) represents the total revenue from ALL products (gasoline, diesel, jet fuel, naphtha, LPG, fuel oil, petcoke, sulfur) minus the cost of crude oil, calculated per barrel of crude processed. Unlike simplified 3-2-1 or 5-3-2 cracks that model only 2-3 products, GRM captures the actual economics of every stream leaving the refinery gate. A refinery producing 15+ products will have a GRM that diverges significantly from any single crack spread formula.", x: "GRM is typically reported in $/bbl of crude throughput and can be calculated on a per-refinery, per-company, or regional benchmark basis. Indian oil marketing companies (OMCs) like IOCL, BPCL, and HPCL report GRM quarterly in their earnings — Reliance Industries reported a GRM of $12.7/bbl in Q3 FY2024, while IOCL reported $7.8/bbl for the same period. The gap reflects Reliance's more complex configuration and ability to process cheaper heavy crudes." },
      { t: "How GRM Is Calculated", h: "Multiply every drop by its price, sum it up, and subtract what you paid for the barrel.", b: "GRM = (Sum of Product Yield% x Product Price for each product) - Crude Oil Cost. For example, if a refinery yields 45% diesel at $92/bbl, 25% gasoline at $88/bbl, 10% naphtha at $70/bbl, 8% fuel oil at $55/bbl, 7% LPG at $65/bbl, and 5% others at $50/bbl, total product revenue is $80.15/bbl. If crude cost is $75/bbl, GRM = $5.15/bbl.", x: "In practice, the calculation must also account for refinery fuel and losses (typically 7-10% of throughput), meaning not all crude input becomes saleable product. A refinery processing 200,000 bbl/day of crude at a $8/bbl GRM generates gross profit of $1.6 million per day or ~$584 million per year before operating costs. Net refining margin (after opex of $2-5/bbl) determines actual profitability — a $8/bbl GRM with $3.5/bbl opex yields $4.5/bbl net margin." },
      { t: "Singapore GRM Benchmark", h: "The scoreboard every Asian refiner checks before morning coffee.", b: "The Singapore complex GRM, published by Reuters and Platts, is the most widely referenced refining margin benchmark in the Asia-Pacific region. It uses Dubai crude as the feedstock input and Singapore-traded product prices (MOPS gasoline, MOPS gasoil, Singapore fuel oil, naphtha Japan) to compute a margin for a hypothetical complex refinery. The Singapore GRM averaged $5-7/bbl over the 2015-2021 period, surged to $15-20/bbl in 2022, and normalized to $6-9/bbl by mid-2024.", x: "The Singapore benchmark assumes a specific refinery configuration with FCC and reformer — approximately 30% gasoil, 25% gasoline, 12% naphtha, 10% jet/kerosene, 10% fuel oil, and 13% LPG/others. Platts publishes separate benchmarks for 'simple' (topping/hydro-skimming) and 'complex' (FCC/hydrocracker) configurations. The spread between complex and simple GRM — called the 'complexity premium' — typically runs $3-5/bbl, representing the economic value of deeper conversion capacity." },
      { t: "Indian Refiner GRM Comparison", h: "Reliance plays in a different league — and the numbers prove it.", b: "Among Indian refiners, Reliance Industries consistently achieves the highest GRM at $10-15/bbl owing to its 1.24 million bbl/day Jamnagar complex with a Nelson Complexity Index of 12.6. Public sector OMCs operate at lower GRMs: IOCL at $5-9/bbl (1.4 million bbl/day across 11 refineries, NCI ~10), BPCL at $6-10/bbl (700,000 bbl/day, 4 refineries), and HPCL at $5-8/bbl (350,000 bbl/day, 2 refineries). The $3-7/bbl gap between Reliance and OMCs represents billions of dollars in annual earnings difference.", x: "Reliance's GRM advantage stems from three factors: (1) the world's largest refining complex allows unmatched crude diet flexibility — it can process over 150 crude grades from ultra-light condensates to heavy sour Venezuelan Merey; (2) deep conversion units (delayed cokers, petcoke gasifiers) eliminate low-value fuel oil; and (3) petrochemical integration captures an additional $2-4/bbl through para-xylene, polypropylene, and polyethylene production from refinery streams." },
      { t: "Factors That Impact GRM", h: "Crude price moves are just the beginning — GRM swings on a dozen variables.", b: "Key GRM drivers include: crude-product price differentials, crude diet (cheaper crudes boost GRM), refinery complexity (converts more low-value into high-value products), product demand seasonality, unplanned outages reducing product supply, and geopolitical events like the Russia-Ukraine war which widened diesel cracks dramatically. Currency movements also matter — a weaker Indian rupee increases GRM in INR terms for Indian refiners selling domestically.", x: "Inventory effects can swing reported GRM by $2-3/bbl quarter to quarter. When crude prices are falling, refineries holding 30-45 days of crude inventory face inventory losses as the replacement cost drops below purchase cost (FIFO accounting). Conversely, in rising markets, inventory gains inflate reported GRM. Reliance mitigates this through shorter crude inventory cycles (15-20 days) enabled by its dedicated SPM terminal receiving VLCCs directly at Jamnagar." }
    ],
    quiz: [
      { q: "How does GRM differ from a crack spread?", o: ["GRM is measured in $/ton while crack spreads use $/bbl", "GRM captures revenue from all refinery products while crack spreads use only 2-3 products", "GRM excludes crude cost while crack spreads include it", "GRM is calculated monthly while crack spreads are daily"], c: 1, e: "GRM accounts for the full product slate (15+ products) of an actual refinery, while crack spreads like the 3-2-1 or 5-3-2 are simplified proxies using only gasoline, diesel, or a handful of products." },
      { q: "Which Indian refiner consistently reports the highest GRM?", o: ["IOCL (Indian Oil Corporation)", "BPCL (Bharat Petroleum)", "Reliance Industries", "HPCL (Hindustan Petroleum)"], c: 2, e: "Reliance Industries achieves GRMs of $10-15/bbl thanks to its massive 1.24 million bbl/day Jamnagar complex with a Nelson Complexity Index of 12.6 and petrochemical integration — significantly above OMCs at $5-10/bbl." },
      { q: "What was the approximate Singapore complex GRM average during the 2015-2021 period?", o: ["$1-3/bbl", "$5-7/bbl", "$12-15/bbl", "$20-25/bbl"], c: 1, e: "The Singapore complex GRM averaged $5-7/bbl during 2015-2021, then surged to $15-20/bbl during the 2022 refining super-cycle before normalizing to $6-9/bbl by 2024." },
      { q: "How can a falling crude price environment negatively impact a refiner's reported GRM?", o: ["Lower crude prices always improve GRM since input costs fall", "Inventory losses occur when crude purchased at higher prices is valued against lower replacement costs", "Falling crude prices reduce product demand automatically", "Regulators mandate lower product prices faster than crude prices fall"], c: 1, e: "Under FIFO accounting, crude purchased weeks earlier at higher prices flows through cost of goods sold while replacement crude is cheaper — creating inventory losses of $2-3/bbl that depress reported GRM even if spot margins are healthy." }
    ]
  },
  {
    id: 3, n: "III", t: "Product Yields & Refinery Configuration", d: "Learn how refinery hardware — from simple distillation to deep conversion units — determines the product slate and directly drives economic performance.",
    concepts: [
      { t: "Simple vs Complex vs Deep Conversion", h: "A topping refinery is a bicycle; a deep conversion complex is a Formula 1 car.", b: "Simple (topping/hydroskimming) refineries only distill crude and desulfurize products — they yield 30-45% fuel oil from heavy crudes and earn the lowest margins ($2-4/bbl). Complex refineries add FCC or hydrocracking to convert heavy fractions into gasoline and diesel, cutting fuel oil yield to 10-15% and earning $6-10/bbl. Deep conversion refineries add cokers and residue upgrading to achieve near-zero fuel oil, processing the cheapest heavy crudes at $10-15/bbl margins.", x: "The economics are stark: fuel oil sells at a $15-25/bbl discount to crude, while gasoline and diesel sell at $5-15/bbl premiums. Each percentage point of fuel oil yield converted to distillate or gasoline adds roughly $0.20-0.40/bbl to GRM. This is why Reliance invested over $6 billion in adding delayed cokers and petcoke gasifiers at Jamnagar — eliminating fuel oil output entirely and converting residue into hydrogen, power, and syngas." },
      { t: "FCC, Hydrocracker & Coker — The Big Three", h: "Three machines that turn black sludge into liquid gold.", b: "The Fluid Catalytic Cracker (FCC) converts vacuum gasoil (VGO) into mainly gasoline (50-55% yield) and LPG (15-20%), using zeolite catalysts at 500-540 degrees C. Hydrocrackers convert VGO into mainly diesel (60-70%) and jet fuel (15-20%) using hydrogen at 350-425 degrees C and 100-200 bar pressure. Delayed cokers thermally crack vacuum residue at 480-510 degrees C into lighter liquids (55-65%), gas (10-15%), and petroleum coke (25-30%).", x: "The choice between FCC and hydrocracker depends on market demand and crude diet. US refineries are FCC-heavy (gasoline demand), while Asian and Middle Eastern refineries favor hydrocrackers (diesel demand). A 60,000 bbl/day hydrocracker costs $1.5-2.5 billion but can add $4-6/bbl to refinery margin. Indian refineries like IOCL's Paradip (300,000 bbl/day) and BPCL's Kochi (310,000 bbl/day) have added hydrocrackers in recent expansions to handle heavier crude diets." },
      { t: "Nelson Complexity Index (NCI)", h: "One number that tells you how sophisticated a refinery really is.", b: "The Nelson Complexity Index assigns a complexity factor to each process unit relative to crude distillation (factor = 1.0), then calculates a weighted sum based on each unit's throughput relative to crude capacity. FCC has a factor of 6.0, hydrocracking 6.0, coking 6.0, catalytic reforming 5.0, and alkylation 11.0. A simple topping refinery has NCI of 2-3, a standard complex refinery 8-10, and world-class facilities like Reliance Jamnagar reach 12.6.", x: "The NCI correlates strongly with GRM — each point of NCI typically adds $0.50-0.80/bbl to margin over a full cycle. Saudi Aramco's new Jazan refinery has NCI of 11, Shell's Pernis (Netherlands) is 11.4, and ExxonMobil's Baytown complex reaches 13.5. However, NCI alone doesn't capture everything — integration with petrochemicals, logistics advantages, and crude access also matter significantly. IOCL's newest refineries target NCI of 11+ while older refineries like Digboi (NCI ~3) operate as simple units." },
      { t: "Yield Patterns by Configuration", h: "Show me your yield table and I'll tell you your profit.", b: "A typical yield from Arab Medium crude (31 API, 2.5% sulfur) changes dramatically by configuration. Simple refinery: 20% naphtha, 15% diesel, 10% kerosene, 10% gasoline, 45% fuel oil. Complex (with FCC): 30% gasoline, 25% diesel, 10% kerosene, 10% naphtha, 8% LPG, 12% fuel oil, 5% losses. Deep conversion (with coker + hydrocracker): 25% diesel, 22% gasoline, 12% jet/kerosene, 10% naphtha, 10% LPG, 8% petcoke, 8% others, 5% losses, 0% fuel oil.", x: "Indian refineries processing a diet of 60% Middle Eastern medium-sour, 20% African light-sweet, and 20% others typically target 42-45% middle distillate (diesel + kerosene), 20-25% gasoline/naphtha, 8-12% LPG, and aim for less than 10% fuel oil. The shift from BS-IV to BS-VI fuel standards in India (April 2020) required $5 billion in hydrotreater investments across the industry to reduce diesel sulfur from 50 ppm to 10 ppm." },
      { t: "How Configuration Affects Economics", h: "Hardware is destiny — the right configuration can mean billions in annual profit difference.", b: "A 200,000 bbl/day refinery upgrading from simple (NCI 5) to complex (NCI 10) might invest $4-6 billion but increase annual GRM by $4-6/bbl, translating to $290-440 million in additional annual gross profit. The payback period is typically 8-12 years at mid-cycle margins. Configuration also determines crude flexibility — complex refineries can process 20-30+ crude grades versus 3-5 for simple refineries, capturing discounts on opportunity crudes.", x: "Reliance's Jamnagar refinery demonstrates the economics at scale: the 660,000 bbl/day DTA refinery and 580,000 bbl/day SEZ refinery together can process everything from ultra-light US condensates (50+ API) to Venezuelan Merey (16 API, 2.5% sulfur). During 2023, when heavy-light crude differentials widened to $8-10/bbl, Reliance's ability to run heavy crudes while less complex refiners could not generated an estimated $2-3/bbl incremental margin advantage." }
    ],
    quiz: [
      { q: "What is the typical fuel oil yield of a simple (topping) refinery processing medium crude?", o: ["5-10%", "15-20%", "30-45%", "50-60%"], c: 2, e: "Simple topping refineries can yield 30-45% fuel oil from medium/heavy crudes because they lack conversion units (FCC, hydrocracker, coker) to upgrade the heavy residual fraction into lighter, more valuable products." },
      { q: "What is the Nelson Complexity Index of Reliance Jamnagar?", o: ["6.5", "9.0", "12.6", "15.2"], c: 2, e: "Reliance Jamnagar has a Nelson Complexity Index of 12.6, making it one of the most complex refining facilities in the world, with FCC, hydrocrackers, delayed cokers, and petcoke gasification units." },
      { q: "Which conversion unit primarily produces diesel and jet fuel?", o: ["Fluid Catalytic Cracker (FCC)", "Hydrocracker", "Delayed Coker", "Catalytic Reformer"], c: 1, e: "Hydrocrackers convert vacuum gasoil into 60-70% diesel and 15-20% jet fuel using hydrogen under high pressure. FCC units are gasoline-focused (50-55% gasoline), while cokers process residue and reformers upgrade naphtha to high-octane gasoline components." },
      { q: "How much incremental GRM does each point of Nelson Complexity typically add?", o: ["$0.05-0.10/bbl", "$0.50-0.80/bbl", "$2.00-3.00/bbl", "$5.00-7.00/bbl"], c: 1, e: "Each point of Nelson Complexity Index typically adds $0.50-0.80/bbl to GRM over a full margin cycle, which is why major refiners invest billions to increase complexity — even a $0.50/bbl improvement on 200,000 bbl/day is $36.5 million annually." }
    ]
  },
  {
    id: 4, n: "IV", t: "Crude Selection Economics", d: "Master the art and science of crude oil selection — understanding how API gravity, sulfur content, and pricing differentials translate into refinery margin.",
    concepts: [
      { t: "Light-Heavy Differential", h: "Not all barrels are created equal — lighter crude means more gasoline, less headache.", b: "Light crude (API > 35) yields more high-value light products (gasoline, naphtha, jet fuel) and less residual fuel oil compared to heavy crude (API < 25). The light-heavy differential — typically measured as Brent minus Dubai or LLS minus Mars — represents the premium the market places on lighter, easier-to-refine grades. This spread historically averages $3-6/bbl but can widen to $10-15/bbl when conversion capacity is tight or narrow to $1-2/bbl when surplus coking capacity exists.", x: "Complex refiners actively exploit the light-heavy differential. When the Brent-Dubai spread widens beyond $5/bbl, it signals that heavy crude is relatively cheap, benefiting refineries with cokers and hydrocrackers that can process it efficiently. Reliance's Jamnagar can swing its crude diet from 100% light to 60%+ heavy grades depending on differentials. In 2023, the Mars-WTI spread averaged $4.50/bbl, while the Brent-Dubai spread averaged $3.20/bbl — both representing opportunity for complex refiners." },
      { t: "Sweet-Sour Spread", h: "Sulfur is the enemy — and removing it costs real money.", b: "Sweet crude (< 0.5% sulfur) commands a premium over sour crude (> 0.5% sulfur) because sour processing requires expensive hydrotreating and hydrodesulfurization units, catalyst replacement, and corrosion-resistant metallurgy. The sweet-sour spread (e.g., Bonny Light minus Arab Heavy) typically ranges $2-5/bbl but spiked to $8-12/bbl after IMO 2020 regulations mandated 0.5% sulfur marine fuel, dramatically increasing demand for low-sulfur products.", x: "Processing sour crude requires hydrogen-rich treating units that cost $500-800 million to install and consume 200-400 scf of hydrogen per barrel. The economics favor sour crude only when the discount exceeds processing cost — typically $1.50-2.50/bbl in additional opex. Saudi Aramco's Arab Light (34 API, 1.8% sulfur) and Arab Heavy (28 API, 2.8% sulfur) price differential to Asian buyers averages $3-4/bbl, set by the Saudi OSP (Official Selling Price) relative to the Oman/Dubai average." },
      { t: "Crude Diet Optimization", h: "The refinery LP model eats 100 crude assays for breakfast and spits out the optimal barrel.", b: "Refineries use linear programming (LP) models to optimize their crude diet — selecting from 50-150 available crude grades to maximize GRM given the refinery's configuration, product demand, quality constraints, and logistics. The LP model evaluates each crude's yield structure, quality properties, and delivered cost to determine the optimal blend. Major refiners like Shell, ExxonMobil, and Reliance run their LP models daily, adjusting crude purchases weeks in advance of processing.", x: "IOCL's centralized crude optimization team in New Delhi manages purchases for all 11 refineries, using Haverly's GRTMPS LP software to evaluate 80+ crude grades monthly. The model considers refinery-specific constraints (distillation capacity, conversion limits, product specs, storage), logistics (port draft limits, pipeline connectivity), and market conditions (crude OSPs, product cracks, freight rates). A well-optimized crude diet can add $0.50-1.50/bbl to GRM versus a sub-optimal selection." },
      { t: "Opportunity Crudes", h: "Distressed barrels, quality challenges, tight windows — but the margin rewards are enormous.", b: "Opportunity crudes are non-standard grades available at significant discounts ($3-10/bbl below benchmark) due to quality challenges (high TAN, high metals, high sulfur), logistical constraints, or seller distress. Examples include Venezuelan Merey (16 API, 2.5% sulfur), Canadian heavy synbit, Iraqi Basrah Heavy (24 API, 3.4% sulfur), and high-TAN West African grades like Dalia. Only complex refineries with the right metallurgy and conversion capacity can capture these discounts.", x: "Reliance pioneered opportunity crude processing in India, building dedicated facilities for Venezuelan crude (which requires heating and special tanks due to its 250+ cSt viscosity). During US sanctions on Venezuela (2019-2023), discounts on Merey widened to $15-20/bbl versus Dubai — but only refiners with crude-specific infrastructure could capture this. High-TAN crudes (TAN > 0.5 mg KOH/g) require 316 stainless steel or Alloy 625 metallurgy in distillation units, an upgrade costing $100-300 million that pays back in 3-5 years through cheaper crude access." },
      { t: "Crude Assay Evaluation", h: "API, sulfur, TBP yields, metals, TAN — five numbers that tell the story of a barrel.", b: "A crude assay is the refiner's bible — a comprehensive laboratory analysis of a crude grade's physical and chemical properties. Key parameters include API gravity (density), sulfur content, TBP (True Boiling Point) distillation yields for each fraction, metals content (vanadium, nickel which poison catalysts), and Total Acid Number (TAN, indicating naphthenic acid corrosion risk). Refiners maintain assay databases of 500+ crude grades and update them as field quality changes over time.", x: "The assay evaluation workflow begins with screening (API, sulfur, price), proceeds to LP modeling (yield prediction, margin estimation), then quality checks (metals impact on catalyst life, TAN impact on metallurgy, compatibility for blending). A single cargo of 2 million barrels of crude priced wrong by $0.50/bbl represents a $1 million error. Saudi Aramco publishes official assays for Arab Extra Light (39 API), Arab Light (33 API), Arab Medium (31 API), and Arab Heavy (28 API), while independent labs like Intertek and SGS provide spot assays for non-standard grades." }
    ],
    quiz: [
      { q: "What does a widening Brent-Dubai spread signal for complex refiners?", o: ["Heavy crude is becoming relatively cheaper, benefiting complex refiners", "Light crude is becoming cheaper, benefiting simple refiners", "Product demand is weakening globally", "OPEC is increasing production quotas"], c: 0, e: "When the Brent-Dubai spread widens, it means heavy/medium crude (priced off Dubai) is cheap relative to light crude (priced off Brent). Complex refiners with cokers and hydrocrackers can process this discounted heavy crude profitably, gaining a margin advantage." },
      { q: "What is the typical additional operating cost of processing sour vs sweet crude?", o: ["$0.10-0.30/bbl", "$1.50-2.50/bbl", "$5.00-8.00/bbl", "$10.00-15.00/bbl"], c: 1, e: "Processing sour crude requires additional hydrotreating consuming 200-400 scf/bbl of hydrogen, catalyst replacement, and corrosion management, adding approximately $1.50-2.50/bbl in extra operating costs versus sweet crude." },
      { q: "What does TAN measure in a crude assay?", o: ["Total Aromatic Naphthenes — the gasoline potential of the crude", "Total Acid Number — naphthenic acid content indicating corrosion risk", "Thermal Activation Number — how easily the crude cracks", "Total Ash and Nitrogen — residual contaminant levels"], c: 1, e: "Total Acid Number (TAN) measures naphthenic acid content in mg KOH/g. High-TAN crudes (>0.5) cause aggressive corrosion in distillation units at 220-400 degrees C, requiring expensive corrosion-resistant metallurgy upgrades but are available at significant discounts." },
      { q: "How much incremental GRM can a well-optimized crude diet add versus sub-optimal selection?", o: ["$0.05-0.10/bbl", "$0.50-1.50/bbl", "$3.00-5.00/bbl", "$8.00-12.00/bbl"], c: 1, e: "A well-optimized crude diet using LP modeling to select from 50-150+ available grades can add $0.50-1.50/bbl to GRM — on a 200,000 bbl/day refinery, that translates to $36-109 million in additional annual gross profit." }
    ]
  },
  {
    id: 5, n: "V", t: "Product Pricing Mechanisms", d: "Understand how refined product prices are discovered, benchmarked, and applied across global and Indian markets — from Platts to trade parity.",
    concepts: [
      { t: "Platts/OPIS Price Discovery", h: "Every afternoon at 4:30 PM Singapore time, the world's product prices are set.", b: "S&P Global Platts is the dominant price reporting agency (PRA) for global petroleum products, publishing benchmark assessments based on their Market-on-Close (MOC) process. During a 30-minute trading window, market participants submit bids, offers, and trades on the Platts eWindow platform, and Platts editors assess the prevailing market value. OPIS (Oil Price Information Service) serves a similar role for US domestic product markets. These assessments become the basis for physical contract pricing worldwide.", x: "The Platts MOC process for Singapore products (MOPS) runs from 4:00-4:30 PM Singapore time and generates assessments for gasoline (92 RON, 95 RON, 97 RON), gasoil (0.05% sulfur, 0.001% sulfur), jet fuel, naphtha, and fuel oil. These are quoted as $/bbl FOB Singapore. Daily traded volumes in the Platts window can reach 5-10 million barrels across products. Argus Media provides competing assessments, and some markets (notably European diesel) are shifting toward Argus pricing after the 2023 Platts methodology controversies." },
      { t: "Asian Product Benchmarks (Singapore MOPS)", h: "Singapore — a tiny island that prices fuel for half the world.", b: "The Mean of Platts Singapore (MOPS) is the primary product pricing benchmark for all of Asia-Pacific, covering over 30 million bbl/day of refinery output across China, India, Japan, South Korea, and Southeast Asia. MOPS gasoline 92 RON, MOPS gasoil 0.001% sulfur, and MOPS jet fuel are the key benchmarks. Refiners sell products at MOPS plus a premium (for domestic sales) or MOPS minus a discount (for distressed cargoes), with premiums/discounts negotiated based on supply-demand tightness.", x: "Indian refiners price their exports at MOPS plus a small premium of $0.50-2.00/bbl for quality (India produces very low sulfur BS-VI products) and location. India exported 63 million tonnes of petroleum products in FY2023, with diesel, petrol, and naphtha as the top exports — all priced off MOPS. Singapore's role as the pricing hub stems from its position as Asia's largest trading and storage center, with 85 million barrels of oil storage capacity on Jurong Island and active trading by Shell, Vitol, Trafigura, and BP." },
      { t: "Import/Export Parity Pricing", h: "Import parity asks: what would it cost to bring this product here? Export parity asks: what could we sell it for abroad?", b: "Import parity price (IPP) = international benchmark price + freight + insurance + customs duty + port charges. Export parity price (EPP) = international benchmark price + FOB premium - freight to export destination. In India, the government introduced Trade Parity Price (TPP) in 2006 as a weighted average: TPP = 80% x Import Parity + 20% x Export Parity, reflecting that India is a net importer of crude but net exporter of some products.", x: "For Indian diesel pricing, Import Parity = MOPS gasoil 0.001%S ($/bbl) x exchange rate (INR/$) / 159 (liters/bbl) + ocean freight (Platts AG-East route, ~$1.50/bbl) + insurance (0.5%) + customs duty (2.5% BCD) + port charges. Export Parity = MOPS gasoil - freight to nearest export market (typically Singapore or East Africa). The 80:20 IPP:EPP weighting was chosen because ~80% of India's incremental petroleum supply comes through imports. Under current market-linked pricing, OMCs use TPP as a reference but adjust retail prices based on competitive dynamics and government guidance." },
      { t: "Indian Administered Pricing Mechanism", h: "Deregulated in theory, guided in practice — India's fuel pricing walks a political tightrope.", b: "India deregulated petrol pricing in June 2010 and diesel in October 2014, allowing OMCs to set retail prices based on international benchmarks. However, LPG (domestic cooking gas) and PDS kerosene remain partially subsidized through direct benefit transfer (DBT) of ~INR 200/cylinder for LPG to Ujjwala beneficiaries. In practice, OMCs froze petrol and diesel prices for extended periods before elections (November 2021 to May 2022, holding prices flat despite crude surging from $70 to $120/bbl), absorbing losses of INR 15,000-20,000 crore.", x: "The retail price build-up in March 2024 Delhi: crude cost INR 45-50/liter, refining margin INR 3-5/liter, freight INR 1-2/liter, customs duty INR 1/liter, central excise INR 19.90/liter (petrol) and INR 15.80/liter (diesel), dealer commission INR 3.80/liter, state VAT ~30% (Delhi). Final retail price: petrol INR 94.72/liter, diesel INR 87.62/liter. Taxes constitute approximately 50-55% of the retail petrol price, making India's fuel among the most heavily taxed globally relative to crude cost." },
      { t: "Trade Parity Formula in Practice", h: "80-20 — the split that balances importer reality with exporter ambition.", b: "The Trade Parity Price formula (TPP = 0.80 x IPP + 0.20 x EPP) is used by Indian OMCs as the starting point for domestic product pricing. For a product where IPP is INR 60/liter and EPP is INR 55/liter, TPP = 0.80 x 60 + 0.20 x 55 = INR 59/liter. This formula was recommended by the Rangarajan Committee (2006) and later endorsed by the Kirit Parikh Committee (2010) as a fair market-reflective mechanism.", x: "The TPP mechanism has practical implications for refiner margins. When export markets are strong (high EPP), the 20% EPP weight limits domestic price increases, effectively subsidizing domestic consumers. Conversely, when export markets are weak, the 80% IPP weight keeps domestic prices elevated relative to export alternatives. For niche products like bitumen and industrial fuels that India neither imports nor exports significantly, OMCs use cost-plus pricing: crude cost + processing cost + margin. The Petroleum Planning and Analysis Cell (PPAC) under MoPNG publishes monthly IPP/EPP/TPP data for all major products." }
    ],
    quiz: [
      { q: "What does MOPS stand for and where is it used?", o: ["Market Opening Price Singapore — a morning assessment for Asian products", "Mean of Platts Singapore — the primary product pricing benchmark for Asia-Pacific", "Monthly Oil Price Survey — a government-published price index", "Mid-day Oil Pricing Standard — an afternoon trading benchmark"], c: 1, e: "MOPS (Mean of Platts Singapore) is the dominant product pricing benchmark for the entire Asia-Pacific region, covering gasoline, diesel, jet fuel, naphtha, and fuel oil, assessed by S&P Global Platts during the 4:00-4:30 PM Singapore MOC window." },
      { q: "What is India's Trade Parity Price (TPP) weighting?", o: ["50% Import Parity + 50% Export Parity", "80% Import Parity + 20% Export Parity", "70% Import Parity + 30% Export Parity", "100% Import Parity"], c: 1, e: "India's TPP formula is 80% Import Parity + 20% Export Parity, recommended by the Rangarajan Committee in 2006, reflecting that ~80% of India's incremental petroleum needs are met through imports." },
      { q: "Approximately what percentage of India's retail petrol price is taxes (excise + VAT)?", o: ["15-20%", "30-35%", "50-55%", "70-75%"], c: 2, e: "Central excise duty (INR 19.90/liter) plus state VAT (~30%) means taxes constitute approximately 50-55% of India's retail petrol price — making Indian fuel among the most heavily taxed globally relative to crude cost." },
      { q: "When was diesel pricing deregulated in India?", o: ["June 2010", "October 2014", "April 2016", "January 2020"], c: 1, e: "India deregulated diesel pricing in October 2014 (petrol was deregulated earlier in June 2010), allowing OMCs to set prices based on international benchmarks — though in practice, prices have been frozen during politically sensitive periods." }
    ]
  },
  {
    id: 6, n: "VI", t: "Indian Basket & Domestic Pricing", d: "Decode the Indian crude basket, trace the rupee-denominated journey from barrel to pump, and understand the legacy of under-recoveries.",
    concepts: [
      { t: "The Indian Basket Formula", h: "72-28 — the two numbers every Indian oil analyst memorizes first.", b: "The Indian basket crude oil price is a weighted average of Dubai/Oman sour crude (72% weight) and Brent sweet crude (28% weight), reflecting the actual crude import mix of Indian refineries. This formula was adopted because over 60% of India's crude imports originate from the Middle East (priced off Dubai/Oman) while the remainder comes from Africa, Americas, and others (priced off Brent). As of early 2024, with Brent at ~$82/bbl and Dubai at ~$80/bbl, the Indian basket price was approximately $80.56/bbl.", x: "The Indian basket weighting was historically 57.5% Dubai + Oman and 42.5% Brent (average of high-low) before being revised to the current 72:28 split to better reflect actual import patterns. PPAC publishes the Indian basket price daily on its website. The basket price is used by the Ministry of Petroleum and Natural Gas for policy planning, subsidy calculations, and fiscal projections. Every $1/bbl change in the Indian basket impacts India's annual import bill by approximately $2 billion, given India imports roughly 4.5-5.0 million bbl/day." },
      { t: "Retail Price Build-Up", h: "From a barrel in the Arabian Gulf to a liter at the Delhi pump — here is every rupee of the journey.", b: "The retail price of petrol/diesel in India builds up from: base crude cost (INR 45-50/liter), refinery transfer price including margin (INR 3-5/liter), freight and pipeline charges (INR 1-2/liter), customs duty on crude (5% BCD, currently reduced to 0% on some occasions), central excise duty (INR 19.90/liter for petrol, INR 15.80/liter for diesel), dealer commission (INR 3.70-3.90/liter), and state VAT/sales tax (varies: 30% in Delhi, 26% in Maharashtra, 39% in Rajasthan). The final pump price varies by INR 8-15/liter across states due to different VAT rates.", x: "The excise duty structure has two components: Basic Excise Duty (BED) and Special Additional Excise Duty (SAED) + Agriculture Infrastructure Development Cess (AIDC). The central government uses excise adjustments as a fiscal tool — excise on petrol was raised from INR 9.48/liter in March 2014 to INR 32.90/liter by May 2020, then reduced in phases to INR 19.90/liter by May 2022 as crude spiked. This mechanism effectively captured the benefit of falling crude prices for government revenue (2014-2020) and partially cushioned consumers during the 2022 spike." },
      { t: "The Under-Recovery Era (2002-2014)", h: "For twelve years, Indian OMCs sold fuel below cost — and the government picked up the tab.", b: "Under-recoveries represented the difference between the import parity price and the government-mandated retail price, which was held artificially low to shield consumers from global price volatility. At peak in FY2013, under-recoveries reached INR 1.61 lakh crore ($30 billion), shared among upstream companies (ONGC, OIL — 40%), government budget subsidy (40%), and OMC absorption (20%). IOCL alone reported under-recoveries of INR 69,542 crore in FY2013, making its retail fuel business deeply unprofitable despite being India's largest refiner.", x: "The under-recovery mechanism created perverse incentives: OMCs had no incentive to control costs or invest in efficiency since losses were compensated; upstream companies like ONGC saw 40% of their profit taken as 'subsidy discount'; and the government's fiscal deficit ballooned. The phased dismantling began with petrol deregulation (June 2010), diesel deregulation (October 2014), and DBT for LPG/kerosene (2015 onwards). By FY2018, under-recoveries effectively dropped to near zero for petrol and diesel, saving the exchequer ~INR 1 lakh crore annually." },
      { t: "Current Market-Linked Regime", h: "Daily price revision was born in June 2017 — welcome to the era of dynamic pricing.", b: "Since June 16, 2017, Indian OMCs revised petrol and diesel prices daily at 6:00 AM based on the previous 15-day rolling average of international product prices and INR/USD exchange rate. This replaced the fortnightly revision mechanism. Under this system, prices should move by INR 0.05-0.20/day in either direction, tracking global markets with a lag. However, OMCs have periodically deviated — freezing prices for extended periods (e.g., November 2021 to May 2022 ahead of state elections) at significant cost to their balance sheets.", x: "The daily pricing formula: Retail price = Trade Parity Price of previous 15 days + excise duty + dealer commission + VAT. The 15-day rolling average smooths out daily volatility. IOCL, BPCL, and HPCL collectively operate ~78,000 retail outlets and typically maintain price parity among themselves (within INR 0.05-0.10) through informal coordination. Private players (Reliance-bp with ~1,500 outlets, Nayara/Rosneft with ~6,500 outlets) have provided limited competitive pressure, occasionally pricing INR 1-2/liter below OMCs to attract volumes." },
      { t: "Impact of Currency on Domestic Prices", h: "When the rupee weakens by one paisa, India's oil bill rises by INR 480 crore per year.", b: "Since crude oil and products are denominated in US dollars, the INR/USD exchange rate directly impacts domestic fuel costs. A 1 INR/USD depreciation increases the cost of India's 5 million bbl/day crude imports by approximately INR 480 crore per year and adds roughly INR 0.45/liter to petrol and diesel retail prices. The rupee's slide from INR 45/USD in 2011 to INR 83/USD in 2024 has effectively doubled the rupee cost of crude even when dollar-denominated prices remained similar.", x: "Indian refiners face a natural partial hedge: crude purchases are in USD (cost side) while domestic product sales are in INR (revenue side). But export revenues are also in USD, and OMCs maintain a 'natural hedge' by matching the currency of import payments against export receipts. RBI regulations allow OMCs to hedge up to 50% of net currency exposure using forwards and options. IOCL and BPCL typically hedge 3-6 months forward. In FY2024, when the rupee was relatively stable at INR 82-83/USD, currency impact on fuel prices was muted at INR 0.50-1.00/liter compared to the INR 5-7/liter swings seen in FY2019 when the rupee fell from 64 to 74." }
    ],
    quiz: [
      { q: "What is the Indian basket crude oil formula?", o: ["50% Dubai + 50% Brent", "72% Dubai/Oman + 28% Brent", "60% Arab Light + 40% WTI", "85% Dubai + 15% Nigerian Bonny Light"], c: 1, e: "The Indian basket is 72% Dubai/Oman (sour crude) + 28% Brent (sweet crude), reflecting India's actual crude import sources — over 60% from the Middle East (Dubai-priced) and the rest from Africa and others (Brent-priced)." },
      { q: "What were India's peak under-recoveries and in which fiscal year?", o: ["INR 50,000 crore in FY2008", "INR 1.01 lakh crore in FY2012", "INR 1.61 lakh crore in FY2013", "INR 2.10 lakh crore in FY2014"], c: 2, e: "Under-recoveries peaked at INR 1.61 lakh crore (~$30 billion) in FY2013, shared among upstream companies (40%), government subsidy (40%), and OMC absorption (20%) — a massive fiscal burden that drove the push for deregulation." },
      { q: "When did India implement daily revision of petrol and diesel prices?", o: ["January 2015", "April 2016", "June 2017", "January 2020"], c: 2, e: "Daily price revision was implemented on June 16, 2017, replacing the fortnightly revision system. Prices are revised at 6:00 AM based on the previous 15-day rolling average of international product prices and exchange rates." },
      { q: "Approximately how much does a 1 INR/USD depreciation add to petrol retail price per liter?", o: ["INR 0.10/liter", "INR 0.45/liter", "INR 1.50/liter", "INR 3.00/liter"], c: 1, e: "A 1 INR/USD depreciation adds approximately INR 0.45/liter to retail petrol and diesel prices, as crude oil and products are dollar-denominated while domestic sales are in rupees." }
    ]
  },
  {
    id: 7, n: "VII", t: "Operating Cost Structure", d: "Break down refinery operating expenses dollar by dollar — from the furnaces consuming 7% of crude throughput to the catalyst worth its weight in gold.",
    concepts: [
      { t: "Energy Costs — The 60% Giant", h: "A refinery's biggest expense isn't crude — it's the energy to transform it.", b: "Energy costs (fuel gas, electricity, steam) account for approximately 55-65% of a refinery's total operating expenditure, excluding crude purchase. A typical complex refinery consumes energy equivalent to 7-9% of its crude throughput — meaning a 200,000 bbl/day refinery burns 14,000-18,000 bbl/day of its own feed as fuel. At $80/bbl crude, this represents $1.1-1.4 million per day in energy cost alone, or $2.00-2.60/bbl of opex.", x: "The primary energy consumers are: crude and vacuum distillation furnaces (30-35% of total energy), catalytic reformer (10-15%), hydrocracker/hydrotreater hydrogen production via steam methane reforming (15-20%), FCC regenerator air blower (5-8%), and steam generation for reboilers and strippers (10-15%). Indian refineries have reduced their specific energy consumption from 80 MBtu/bbl (million BTU per barrel) in the early 2000s to 55-65 MBtu/bbl through waste heat recovery, combined heat and power (CHP), and advanced process control. Reliance Jamnagar operates at approximately 50 MBtu/bbl — near world-class levels." },
      { t: "Catalyst Costs", h: "A few tons of precious-metal-laced pellets standing between you and off-spec product.", b: "Catalysts are specialized materials that enable refinery reactions — FCC catalysts (zeolite-based, $2,000-4,000/ton, consumed at 0.5-1.0 lb per barrel of feed), hydrocracking catalysts (nickel-molybdenum or nickel-tungsten on alumina, $15,000-30,000/ton, replaced every 2-4 years), and reforming catalysts (platinum on alumina, $80,000-150,000/ton due to platinum content). Total catalyst cost for a 200,000 bbl/day complex refinery is $30-60 million per year, or $0.40-0.80/bbl.", x: "FCC catalyst is a continuous expenditure because it physically degrades (attrites) during the fluidized bed cycle and is continuously added and withdrawn. A 60,000 bbl/day FCC unit consumes 30-60 tons/day of fresh catalyst ($60,000-240,000/day). Hydrocracking and hydrotreating catalysts are loaded in fixed beds and deactivate over 2-4 year cycles due to coke and metals deposition — regeneration (burning off coke) can extend life by one cycle, but eventual replacement costs $10-20 million per reactor load. Indian catalyst suppliers include HPCL's subsidiary CPCL and imports from UOP (Honeywell), Haldor Topsoe, and Albemarle." },
      { t: "Maintenance & Turnaround Cycles", h: "Every 4-5 years, the refinery shuts down for surgery — and the bill runs into hundreds of millions.", b: "Planned maintenance turnarounds (shutdowns) occur every 4-6 years for major process units, lasting 30-45 days, and cost $100-300 million for a large complex refinery. During turnarounds, the entire unit is opened for inspection, equipment replacement, catalyst changeout, and integrity repairs. A 200,000 bbl/day refinery losing 35 days of production at $8/bbl GRM also forfeits ~$56 million in lost margin, making turnaround planning and execution a critical economic lever.", x: "Indian refineries typically schedule turnarounds during the monsoon season (July-September) when domestic demand is lower and tanker freight is seasonally cheaper for crude delivery. IOCL's turnaround at its 300,000 bbl/day Paradip refinery in 2023 was completed in 32 days (versus 40-day plan), saving approximately $20 million in lost production. Advanced practices include predictive maintenance using vibration analysis, infrared thermography, and AI-based equipment health monitoring — BPCL's Kochi refinery claims 15% reduction in maintenance costs since implementing digital twin technology." },
      { t: "Labor, Utilities & Chemicals", h: "People, water, and chemicals — the remaining 15-20% of the opex pie.", b: "Labor costs for a 200,000 bbl/day refinery typically involve 800-1,500 permanent employees plus 2,000-5,000 contract workers, costing $50-150 million annually depending on location (US/Europe high, India/Middle East lower). Utilities include cooling water (2-4 gallons per gallon of crude processed), process water, and nitrogen for blanketing and purging. Chemical costs cover caustic soda (for treating), MEA/MDEA (for sulfur recovery), antifoulants, corrosion inhibitors, and demulsifiers — totaling $0.15-0.30/bbl.", x: "Indian refinery labor costs are structurally lower than Western peers: a process engineer earns INR 12-25 lakh/year ($15,000-30,000) versus $100,000-150,000 in the US Gulf Coast. This gives Indian refiners a $0.30-0.50/bbl opex advantage. However, water scarcity is an emerging cost driver — IOCL's Gujarat refinery and Reliance Jamnagar both invested in zero liquid discharge (ZLD) systems costing INR 500-800 crore, while BPCL Kochi sources water from 40 km away. Chemical costs have risen 15-25% since 2021 due to supply chain disruptions in caustic soda (linked to chlor-alkali plant closures in Europe)." },
      { t: "Opex Per Barrel Benchmarks", h: "$2-5 per barrel — the narrow band that separates world-class from laggard.", b: "Global refinery operating costs (excluding crude purchase) typically range $2-5/bbl for large complex refineries: $2.00-2.50/bbl for low-cost operators (Middle East, India), $3.00-4.00/bbl for mid-range (US Gulf Coast, South Korea), and $4.00-5.50/bbl for high-cost regions (Northwest Europe, Japan). Saudi Aramco's refineries operate at approximately $2.20/bbl, Reliance at $2.50/bbl, IOCL at $3.00-3.50/bbl, and European refineries at $4.00-5.00/bbl. The difference is driven by energy costs, labor, regulatory compliance, and scale.", x: "The opex composition for a typical Indian refinery at $3.00/bbl: energy $1.70 (57%), catalysts and chemicals $0.45 (15%), maintenance $0.35 (12%), labor $0.25 (8%), and others $0.25 (8%). Scale matters enormously — a 400,000 bbl/day refinery achieves $0.30-0.50/bbl lower opex than a 100,000 bbl/day refinery through fixed cost dilution. This is why consolidation continues globally: uncompetitive small refineries (< 100,000 bbl/day) with opex above $5/bbl face closure risk when GRMs cycle down below $6-7/bbl, as seen with the closure of Shell's Convent refinery (240,000 bbl/day, high energy costs) and LyondellBasell's Houston refinery (264,000 bbl/day) in 2023." }
    ],
    quiz: [
      { q: "What percentage of refinery opex do energy costs typically represent?", o: ["20-30%", "35-45%", "55-65%", "75-85%"], c: 2, e: "Energy costs (fuel gas, electricity, steam) account for 55-65% of total refinery operating expenditure. A complex refinery consumes the equivalent of 7-9% of its crude throughput as energy, making energy efficiency the single biggest lever for opex reduction." },
      { q: "How much does a typical turnaround cost for a large complex refinery?", o: ["$10-30 million", "$100-300 million", "$500 million-1 billion", "$1-3 billion"], c: 1, e: "Planned maintenance turnarounds cost $100-300 million for large complex refineries and occur every 4-6 years, lasting 30-45 days. Additional lost production margin of $40-80 million makes turnaround optimization critical." },
      { q: "What is the approximate opex per barrel for a world-class Indian refinery like Reliance?", o: ["$0.50/bbl", "$2.50/bbl", "$4.50/bbl", "$6.00/bbl"], c: 1, e: "Reliance Jamnagar operates at approximately $2.50/bbl opex, among the lowest globally, driven by massive scale (1.24 million bbl/day), low Indian labor costs, and energy self-sufficiency through petcoke gasification." },
      { q: "How often are FCC catalysts typically replaced in a refinery?", o: ["They are continuously added and withdrawn — not batch-replaced", "Every 6 months in a planned changeout", "Every 2-4 years like hydrocracking catalysts", "Every turnaround cycle (4-6 years)"], c: 0, e: "FCC catalysts undergo continuous addition and withdrawal because the catalyst physically degrades (attrites) during the fluidized bed cracking-regeneration cycle. A 60,000 bbl/day FCC consumes 30-60 tons/day of fresh catalyst, unlike fixed-bed catalysts that are batch-replaced every 2-4 years." }
    ]
  },
  {
    id: 8, n: "VIII", t: "Inventory Management & Valuation", d: "Learn how crude and product inventory timing, valuation methods, and storage economics can swing reported profits by hundreds of millions of dollars.",
    concepts: [
      { t: "FIFO vs LIFO vs Weighted Average", h: "Three accounting methods, three very different profit numbers from the same barrel.", b: "Under FIFO (First-In-First-Out), the oldest inventory cost is matched to revenue first — in a rising price environment, this understates costs and overstates profits (inventory gains). Under LIFO (Last-In-First-Out), the newest (highest) cost is matched first, producing lower reported profits but more accurate current-cost economics. Weighted average uses the blended cost of all inventory. Indian refiners follow Ind-AS (aligned with IFRS) which effectively mandates FIFO or weighted average — LIFO is not permitted under IFRS.", x: "The choice of inventory method can swing quarterly profits significantly. Consider a refiner holding 30 days of crude inventory (6 million barrels at 200,000 bbl/day throughput) when crude rises $10/bbl in a quarter: under FIFO, the $60 million inventory gain flows through as higher reported GRM. Under LIFO, this gain would be deferred. Shell, which used LIFO until switching to FIFO under IFRS, reports 'CCS (Current Cost of Supply) earnings' to strip out inventory effects — analysts prefer CCS as a truer picture of operational performance." },
      { t: "Inventory Gains & Losses in Volatile Markets", h: "Rising crude: windfall on your tank. Falling crude: a write-down nightmare.", b: "Inventory gains occur when crude purchased at lower prices is sold as products priced at current higher levels (FIFO effect), while inventory losses occur in falling markets. In Q2 2022, when Brent surged from $98 to $123/bbl, Reliance reported an estimated $500 million inventory gain that inflated its GRM by $2-3/bbl. Conversely, in Q4 2022 when crude fell from $100 to $82/bbl, Indian OMCs reported inventory losses of $1-2/bbl, depressing reported GRM below actual spot margins.", x: "Analysts adjust reported GRM for inventory effects to assess 'core' or 'underlying' GRM. The adjustment formula: Core GRM = Reported GRM - (Average crude inventory days x daily crude price change over the quarter / total throughput). For example, IOCL with 25 days of crude inventory during a quarter where crude fell $15/bbl would see an inventory loss of approximately $1.50/bbl (25/90 x $15 x correction factor). Credit Suisse and Morgan Stanley India oil sector reports routinely publish inventory-adjusted GRM tables." },
      { t: "Strategic Crude Stock Timing", h: "Buy low, store, process later — simple in theory, worth millions in practice.", b: "Refineries with excess crude storage capacity can practice crude stock timing — purchasing additional crude during price dips and drawing down during price spikes. India's Strategic Petroleum Reserve (SPR) facilities at Visakhapatnam (1.33 MMT), Mangalore (1.50 MMT), and Padur (2.50 MMT) hold approximately 5.33 million metric tonnes (39 million barrels), covering about 9.5 days of India's crude imports. Commercial crude storage at refineries typically holds 15-30 days of throughput.", x: "During the COVID-19 price crash in April 2020, when crude briefly went negative, India's SPR facilities were filled at approximately $19/bbl — generating a strategic saving of $20-30/bbl versus 2021 prices. ISPRL (Indian Strategic Petroleum Reserves Limited) also leased half of its Padur and Mangalore caverns to Abu Dhabi's ADNOC, which stored crude and agreed to supply it to Indian refiners during emergencies. Commercial refiners also benefited: MRPL (Mangalore Refinery) purchased spot cargoes at record-low prices, contributing to its strongest-ever GRM of $7.2/bbl in Q1 FY2021." },
      { t: "Tank Farm Economics", h: "Steel and land — the unsexy infrastructure that makes or breaks crude flexibility.", b: "A refinery's tank farm represents 15-25% of its total capital investment and includes crude storage (10-20 tanks of 50,000-100,000 cubic meters each), intermediate storage for process feeds, and product storage (gasoline, diesel, jet fuel, LPG in pressurized spheres). A 100,000 cubic meter floating-roof crude tank costs $8-15 million to build and holds approximately 630,000 barrels. Tank farms require firefighting systems (foam), vapor recovery, dike walls for secondary containment, and gauging/measurement systems.", x: "Tank farm utilization directly impacts working capital. A refinery holding 25 days of crude inventory at $80/bbl and 200,000 bbl/day throughput has $400 million locked in crude inventory alone, plus $100-150 million in product inventory. Reducing average crude holding from 25 to 20 days frees $80 million in working capital. Reliance optimizes tank farm usage through its single-point mooring (SPM) facility that receives VLCCs (2 million barrel cargoes) directly, reducing the need for intermediate port storage and cutting crude-in-transit time by 3-5 days compared to refiners relying on lightering at anchorage." },
      { t: "Pipeline Fill & Line Pack", h: "The crude you can't sell, the product you can't bill — trapped in the pipeline.", b: "Pipeline fill (or line pack) represents the volume of crude or product physically inside pipeline infrastructure at any point — this inventory is 'trapped' and cannot be monetized until displaced. India's pipeline network (IOCL: 15,000+ km, BPCL: 3,000+ km, HPCL: 3,700+ km) holds millions of barrels of line fill. A 1,000 km, 30-inch diameter pipeline holds approximately 600,000 barrels of line fill worth $48 million at $80/bbl — this is essentially interest-free locked capital.", x: "Line pack management becomes critical during product transitions and interface tracking. When a pipeline switches from diesel to petrol, the interface (mixed product) of 3,000-10,000 barrels must be segregated and reprocessed — representing both a physical loss and a quality risk. GAIL's LPG pipelines and IOCL's main trunk pipelines use batch scheduling software (typically from Schneider Electric or ABB) to minimize interface volumes. On the crude side, offshore pipeline fill from SPMs to the refinery tank farm (typically 10-30 km) represents 50,000-150,000 barrels of permanently locked inventory — accounted for as a capital asset but tying up working capital throughout the asset's life." }
    ],
    quiz: [
      { q: "Why does FIFO accounting produce inventory gains during a rising crude price environment?", o: ["FIFO allows refiners to revalue inventory at market price each quarter", "FIFO matches older (cheaper) crude costs against current (higher) product revenues", "FIFO applies a gain adjustment factor based on price movements", "FIFO delays recognition of crude purchases until products are sold"], c: 1, e: "Under FIFO, the first (oldest and cheapest) crude cost is expensed first. When crude prices rise, the refiner processes crude purchased weeks ago at lower prices while selling products at current higher prices — the cost-revenue mismatch creates inventory gains that inflate reported GRM." },
      { q: "What is India's total Strategic Petroleum Reserve capacity?", o: ["15 million barrels (2 days of imports)", "39 million barrels (~9.5 days of imports)", "100 million barrels (25 days of imports)", "200 million barrels (50 days of imports)"], c: 1, e: "India's SPR holds 5.33 million metric tonnes (approximately 39 million barrels) across three locations: Visakhapatnam (1.33 MMT), Mangalore (1.50 MMT), and Padur (2.50 MMT), covering about 9.5 days of crude imports." },
      { q: "How much working capital does a 200,000 bbl/day refinery lock up in 25 days of crude inventory at $80/bbl?", o: ["$40 million", "$100 million", "$400 million", "$1 billion"], c: 2, e: "Working capital = 200,000 bbl/day x 25 days x $80/bbl = $400 million. This enormous capital lock-up is why reducing inventory days is a key treasury optimization — cutting from 25 to 20 days frees $80 million." },
      { q: "What is pipeline fill (line pack)?", o: ["The maximum flow rate a pipeline can sustain", "The volume of product physically inside the pipeline that cannot be monetized until displaced", "The minimum pressure required to keep product flowing", "The safety buffer maintained in pipeline storage tanks"], c: 1, e: "Pipeline fill is the volume of crude or product physically trapped inside pipeline infrastructure at any time. This inventory is locked and cannot be sold until displaced by new product, representing permanently committed working capital." }
    ]
  },
  {
    id: 9, n: "IX", t: "Refinery Benchmarking", d: "Discover how the global refining industry measures performance using the Solomon methodology, energy indices, and competitive quartile rankings.",
    concepts: [
      { t: "Solomon Benchmarking Methodology", h: "Every two years, the world's refineries open their books to one company — and find out where they truly stand.", b: "Solomon Associates (now part of HSB) conducts the world's most comprehensive refinery benchmarking study, covering 500+ refineries globally representing over 85% of world capacity. Refineries submit detailed operational, financial, and maintenance data, which Solomon normalizes for configuration, crude slate, product quality, and location to enable apples-to-apples comparison. Results are presented in quartile rankings: 1st quartile (top 25%) represents best-in-class performance, while 4th quartile operators face pressure to improve or consider closure.", x: "The Solomon study has been conducted biennially since 1980 and is considered the gold standard for refinery performance assessment. Participation is confidential — individual refinery results are shared only with the participating refinery and shown as anonymous percentile rankings to others. Key metrics include: energy intensity, maintenance cost, staffing efficiency, mechanical availability, yield performance, and overall refinery competitiveness. Indian OMCs participate actively — IOCL has achieved 1st quartile ranking for several of its newer refineries (Paradip, Panipat) while older units (Digboi, Haldia) typically rank in 2nd-3rd quartile." },
      { t: "Energy Intensity Index (EII)", h: "The single most important number in refinery operations — how much energy you burn per barrel of complexity.", b: "The Solomon Energy Intensity Index (EII) measures a refinery's actual energy consumption against a standard baseline, normalized for complexity and capacity. An EII of 100 means the refinery consumes exactly the baseline amount; below 100 means better-than-baseline efficiency, above 100 means worse. Global 1st quartile refineries achieve EII of 75-85, while 4th quartile operators exceed 110-120. The EII baseline is periodically updated to reflect industry-wide efficiency improvements.", x: "Indian refinery EII performance has improved dramatically: IOCL's average EII dropped from 115 in 2005 to 92 in 2022, while Reliance Jamnagar operates at EII of approximately 78 — firmly in the global 1st quartile. Key EII improvement levers include: waste heat recovery from flue gas and process streams (saves 3-5 EII points), pinch analysis for heat exchanger network optimization (2-4 points), variable frequency drives on pumps and compressors (1-2 points), and advanced process control/real-time optimization (2-3 points). Every 1-point EII improvement at a 200,000 bbl/day refinery saves approximately $1-2 million per year in energy costs." },
      { t: "Maintenance Cost Index", h: "What you spend on wrenches, welders, and spare parts — normalized for fair comparison.", b: "The Solomon maintenance cost index measures total maintenance expenditure (labor, materials, contractor costs for routine maintenance, reliability programs, and turnarounds) per unit of complexity. 1st quartile refineries spend less by maintaining better — through predictive techniques, optimized turnaround planning, and reliability-centered maintenance (RCM). Typical maintenance costs range from $1.50-2.00/bbl for 1st quartile to $3.00-4.50/bbl for 4th quartile, with turnaround costs averaged over the cycle.", x: "The counterintuitive finding from Solomon studies is that lower maintenance spending does NOT always correlate with better performance — refineries that under-invest in maintenance face higher unplanned downtime, which is far more expensive than planned maintenance. The optimal strategy balances predictive/preventive investment against corrective costs. Indian refineries have adopted reliability-based maintenance: BPCL Kochi's RBI (Risk-Based Inspection) program reduced inspection costs by 30% while maintaining mechanical availability above 95%. HPCL Mumbai refinery invested INR 200 crore in a predictive analytics platform that reduced unplanned shutdowns by 25% in its first two years." },
      { t: "Solomon Quartile Performance", h: "First quartile isn't just a ranking — it's worth $200 million a year for a large refinery.", b: "The gap between 1st and 4th quartile refineries in the Solomon study is staggering: approximately $2-4/bbl in total competitiveness, translating to $150-300 million annually for a 200,000 bbl/day refinery. 1st quartile refineries achieve 95-97% mechanical availability versus 88-92% for 4th quartile, EII of 75-85 versus 110-120, and maintenance costs 40-50% lower per unit of complexity. These differences determine which refineries survive margin downturns and which face permanent closure.", x: "Solomon also tracks personnel productivity: 1st quartile refineries employ 2.0-3.0 staff per 1,000 bbl/day of equivalent distillation capacity (EDC) versus 5.0-8.0 for 4th quartile. US refineries have undergone significant workforce rationalization since 2000, reducing average staffing from 4.5 to 2.8 per 1,000 bbl/day EDC through automation and multiskilling. Indian refineries average 3.5-5.0 staff per 1,000 bbl/day EDC — above global best practice but offset by lower per-employee costs. IOCL's target is to reach 3.0 by 2027 through digital transformation and automation investments." },
      { t: "How Indian Refiners Compare Globally", h: "India punches above its weight — but the gap with the global elite remains real.", b: "Indian refineries have shown strong improvement trajectory in Solomon rankings: IOCL moved from predominantly 3rd quartile in 2008 to 2nd-1st quartile for most metrics by 2022 across its newer refineries. Reliance Jamnagar consistently ranks in the global 1st quartile across energy efficiency, yield performance, and operating cost. BPCL Kochi has achieved 1st quartile EII following its $4 billion expansion and integrated refinery-petrochemical complex (IREP). Overall, India's refining sector is considered mid-to-upper tier globally.", x: "India's competitive advantages include: low labor costs ($0.30-0.50/bbl advantage vs Western refineries), large refinery sizes (average 180,000 bbl/day vs global average of 100,000 bbl/day), recent vintage (newer equipment is more efficient), and strategic location between Middle Eastern crude supply and Asian product demand. Disadvantages include: higher energy costs than Middle Eastern refiners (who use $1-2/MMBtu gas vs India's $6-10/MMBtu), complex regulatory environment, and infrastructure constraints (port draft limits, pipeline capacity). By 2030, India plans to expand refining capacity from 254 MMTPA (5.1 million bbl/day) to 310 MMTPA (6.2 million bbl/day), with all new capacity at NCI > 11." }
    ],
    quiz: [
      { q: "How many refineries typically participate in the Solomon benchmarking study?", o: ["50-100", "200-300", "500+ covering 85%+ of world capacity", "All refineries globally — participation is mandatory"], c: 2, e: "Solomon Associates covers 500+ refineries representing over 85% of global refining capacity. Participation is voluntary but considered essential for any serious refiner — results are confidential and anonymized for comparative purposes." },
      { q: "What does an Energy Intensity Index (EII) of 85 indicate?", o: ["The refinery uses 85% more energy than baseline", "The refinery is 15% more energy-efficient than the Solomon baseline", "The refinery has 85% mechanical availability", "The refinery processes 85 types of crude grades"], c: 1, e: "An EII of 85 means the refinery uses 15% less energy than the Solomon baseline (EII 100). This puts it in the 1st quartile range (75-85), indicating world-class energy efficiency — well ahead of 4th quartile operators at EII 110-120." },
      { q: "What is the approximate annual value of the gap between 1st and 4th quartile performance for a 200,000 bbl/day refinery?", o: ["$10-30 million", "$50-80 million", "$150-300 million", "$500 million-1 billion"], c: 2, e: "The 1st-to-4th quartile gap is $2-4/bbl in total competitiveness, translating to $150-300 million annually for a 200,000 bbl/day refinery — driven by differences in energy efficiency, maintenance costs, mechanical availability, and yield performance." },
      { q: "What is the Solomon 1st quartile staffing benchmark per 1,000 bbl/day of capacity?", o: ["0.5-1.0 staff", "2.0-3.0 staff", "5.0-7.0 staff", "10.0-15.0 staff"], c: 1, e: "1st quartile refineries employ 2.0-3.0 staff per 1,000 bbl/day of equivalent distillation capacity, achieved through automation, multiskilling, and digital transformation. Indian refineries currently average 3.5-5.0 and are working to reach 3.0 by 2027." }
    ]
  },
  {
    id: 10, n: "X", t: "Margin Optimization Strategies", d: "Explore the advanced techniques refiners use to squeeze every last dollar from each barrel — from LP models to digital twins and petrochemical integration.",
    concepts: [
      { t: "LP Modeling for Crude Selection", h: "Linear programming — where mathematics meets petroleum to find the perfect barrel.", b: "Linear Programming (LP) models are the cornerstone of refinery planning and optimization, solving systems of thousands of equations to determine the optimal crude diet, operating conditions, and product slate that maximize GRM subject to constraints. Industry-standard LP platforms include Haverly GRTMPS, Aspen PIMS, and Honeywell's Spiral — each costing $500,000-2,000,000 in licensing. A typical refinery LP model contains 2,000-10,000 variables and 1,000-5,000 constraints representing process unit capacities, product quality specifications, and material balances.", x: "The LP model workflow: (1) crude assay evaluation — input yield vectors and quality properties for 50-150 crude grades; (2) define constraints — unit capacities, product specs (BS-VI sulfur limits, octane requirements), blend ratios, contractual obligations; (3) define objective — maximize GRM or minimize crude cost; (4) solve — the simplex algorithm finds the optimal solution in seconds; (5) sensitivity analysis — shadow prices reveal the marginal value of relaxing each constraint. IOCL runs monthly LP optimization for each of its 11 refineries plus a corporate-level multi-refinery optimization that allocates crude cargoes across the system." },
      { t: "Product Slate Optimization", h: "More diesel or more petchem naphtha? The LP knows — and the answer changes every week.", b: "Product slate optimization involves adjusting refinery operating conditions and blending to shift production toward highest-margin products as market conditions change. When diesel cracks are $5/bbl above gasoline cracks, the refiner maximizes middle distillate mode — increasing hydrocracker severity, reducing FCC throughput, and routing naphtha to petrochemical feed rather than gasoline blending. A well-managed 200,000 bbl/day refinery can swing 5-10% of its product slate between gasoline-maximum and diesel-maximum mode, worth $0.50-1.50/bbl in incremental margin.", x: "Real-time product optimization requires coordination across planning, operations, and trading. Shell's 'Smart Margin' system and ExxonMobil's 'Digital Refinery' platform integrate LP planning models with real-time process control (APC — Advanced Process Control) and market pricing to adjust operating targets every 4-8 hours. Indian refiners are catching up: Reliance uses a proprietary integrated margin management system, while IOCL's PRISM initiative connects its refineries to a centralized optimization center in Delhi. Product quality giveaway reduction — producing exactly at the specification limit rather than above — can save $0.20-0.50/bbl through reduced hydrogen consumption, energy savings, and component optimization." },
      { t: "Energy Efficiency Projects", h: "The cheapest barrel of oil is the one you don't burn in your own furnace.", b: "Energy efficiency projects offer the highest returns in refinery capital allocation, with typical payback periods of 1-3 years versus 8-12 years for new process units. Key projects include: waste heat recovery (capturing energy from flue gas, cooling water, and hot process streams using organic Rankine cycle or heat exchangers — saves $3-8 million/year per major unit), combined heat and power cogeneration (producing electricity and steam simultaneously at 80%+ efficiency — IOCL's cogen units save $50-100 million/year system-wide), and furnace revamps (oxygen-enriched combustion, low-NOx burners, air preheating — 3-5% fuel savings).", x: "Advanced process control (APC) is the single most impactful energy efficiency technology: by continuously optimizing operating variables (temperatures, pressures, flows) to their economic optimum rather than conservative operator setpoints, APC reduces energy consumption by 3-8% per unit. A crude distillation unit APC project costing $500,000-1,000,000 saves $2-5 million/year — a payback of 2-6 months. Honeywell, AspenTech, and Yokogawa are leading APC vendors. BPCL has deployed APC across all units at Kochi and Mumbai, reporting cumulative savings of INR 400 crore since implementation." },
      { t: "Petrochemical Integration Benefits", h: "Why stop at fuels when the same barrel can make plastics, fibers, and rubber worth 2-3x more?", b: "Integrated refinery-petrochemical complexes capture $2-5/bbl in additional margin by converting low-value refinery streams (naphtha, propylene, butadiene, para-xylene precursors) into high-value petrochemicals. Reliance's Jamnagar complex produces 15 MMTPA of petrochemicals alongside its 1.24 million bbl/day refining capacity, generating an estimated $3-4/bbl premium over standalone refining. Globally, the 'crude-to-chemicals' ratio (percentage of crude converted to chemicals rather than fuels) is targeted at 25-40% by advanced complexes versus 8-12% for traditional refineries.", x: "Saudi Aramco's Ras Tanura refinery integrated with SATORP and the planned 400,000 bbl/day Shaheen project targets 50%+ crude-to-chemicals. South Korea's Hyundai Oilbank-Lotte Chemical integration and China's Hengli Petrochemical (400,000 bbl/day refinery with 2.5 MMTPA PX/PTA) represent the new paradigm. In India, IOCL's Paradip refinery added a 700,000 TPA polypropylene unit, HPCL is building a 1.5 MMTPA petrochemical complex at Barmer (Rajasthan), and BPCL Kochi's IREP project integrates acrylic acid, oxo-alcohols, and propylene derivatives — collectively targeting $1-2/bbl GRM uplift through integration." },
      { t: "Digital Twins for Operations", h: "A virtual copy of your entire refinery, running 10,000 scenarios before breakfast.", b: "A digital twin is a real-time virtual replica of the physical refinery, integrating process simulation models (Aspen HYSYS, PRO/II), operational data from 50,000-200,000 instrument tags, and predictive analytics to optimize performance and predict failures. The digital twin enables 'what-if' scenario testing — what happens to GRM if we switch crude grade, reduce throughput by 10%, or increase hydrocracker severity? Shell's Pernis refinery digital twin reportedly saves $10-20 million annually through improved yield prediction and reduced unplanned downtime.", x: "Indian refiners are investing heavily in digital twins: IOCL allocated INR 3,000 crore for its Digital Transformation initiative covering all 11 refineries, with Panipat and Gujarat as pilot sites. BPCL's Kochi refinery implemented a comprehensive digital twin with Honeywell's Connected Plant platform, claiming 1.5% throughput improvement and 2% energy reduction — worth approximately $30-40 million annually for a 310,000 bbl/day refinery. Reliance uses proprietary AI/ML models for catalyst deactivation prediction (saving $10-15 million/year in catalyst costs), fouling prediction for heat exchangers (saving 2-3% energy through optimized cleaning schedules), and product quality prediction reducing off-spec production by 40%. The total value of digital transformation for a large Indian refinery is estimated at $50-100 million per year when fully deployed." }
    ],
    quiz: [
      { q: "What is the typical cost of an industry-standard LP modeling platform like Haverly GRTMPS?", o: ["$10,000-50,000", "$100,000-250,000", "$500,000-2,000,000", "$5,000,000-10,000,000"], c: 2, e: "Industry-standard LP platforms (Haverly GRTMPS, Aspen PIMS, Honeywell Spiral) cost $500,000-2,000,000 in licensing, but their ability to optimize crude selection and product slate makes the payback period very short — often months for a large refinery." },
      { q: "How much incremental margin can petrochemical integration add to a refinery?", o: ["$0.10-0.30/bbl", "$0.50-1.00/bbl", "$2-5/bbl", "$10-15/bbl"], c: 2, e: "Integrated refinery-petrochemical complexes capture $2-5/bbl in additional margin by converting low-value streams into high-value chemicals. Reliance Jamnagar generates an estimated $3-4/bbl premium through its 15 MMTPA petrochemical production alongside refining." },
      { q: "What is the typical payback period for an Advanced Process Control (APC) project on a crude distillation unit?", o: ["2-6 months", "2-3 years", "5-7 years", "10-12 years"], c: 0, e: "APC projects on major refinery units like crude distillation cost $500,000-1,000,000 but save $2-5 million/year through 3-8% energy reduction and optimized operation — yielding a remarkable payback of just 2-6 months." },
      { q: "What 'crude-to-chemicals' ratio do advanced integrated complexes target?", o: ["5-8%", "8-12%", "25-40%", "80-95%"], c: 2, e: "Advanced integrated complexes target 25-40% crude-to-chemicals conversion versus 8-12% for traditional refineries. Saudi Aramco's Shaheen project even targets 50%+, reflecting the global shift toward maximizing chemical output as fuel demand is expected to plateau." }
    ]
  }
];

const badgeDefs = [
  { id: "first", i: "\ud83c\udf1f", n: "First Step", d: "Complete your first chapter" },
  { id: "half", i: "\ud83d\udcda", n: "Halfway There", d: "Complete 5 chapters" },
  { id: "scholar", i: "\ud83c\udf93", n: "Refining Scholar", d: "Complete all chapters" },
  { id: "s3", i: "\ud83d\udd25", n: "On Fire", d: "3-chapter streak" },
  { id: "s5", i: "\u26a1", n: "Unstoppable", d: "5-chapter streak" },
  { id: "x500", i: "\ud83d\udcb0", n: "XP Hunter", d: "Earn 500 XP" },
  { id: "x1k", i: "\ud83d\udc8e", n: "XP Master", d: "Earn 1000 XP" },
  { id: "ace", i: "\ud83c\udfc6", n: "Perfect Score", d: "100% on any quiz" },
  { id: "speed", i: "\u23f1\ufe0f", n: "Speed Demon", d: "Finish a quiz in under 30 seconds" },
  { id: "owl", i: "\ud83e\udd89", n: "Night Owl", d: "Study after 10 PM" }
];
